name: C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++ clang-tidy cppcheck valgrind

      - name: Create Build Directory
        run: mkdir build

      - name: Build with CMake
        run: |
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          cmake --build .

      - name: Run CppCheck
        run: cppcheck --enable=all --inconclusive --std=c++17 ./src ./include

      - name: Run clang-tidy
        run: |
          clang-tidy src/*.cpp -- -I./include -std=c++17

      - name: Run Tests
        run: |
          cd build
          ctest --output-on-failure

      - name: Run Valgrind on Tests
        run: |
          cd build
          valgrind --leak-check=full --error-exitcode=1 ./GraphAlgorithmTests