name: C++ Build, Test, and Analysis

on:
  push:
  pull_request:

jobs:
     dummy-job:
       runs-on: ubuntu-latest

       steps:
       - name: Run dummy step
         run: echo "Dummy. Нужен только, чтобы проходил ci в этом PR, так как нет файлов с кодом!!!!"
